server:
  port: 8080
vaadin:
  allowed-packages: 'com.vaadin,org.vaadin,dev.hilla,com.example.application'
spring:
  datasource:
    url: '${SPRING_DATASOURCE_URL}'
    username: '${SPRING_DATASOURCE_USER}'
    password: '${SPRING_DATASOURCE_PASSWORD}'
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true