server:
  port: 8888
vaadin:
  launch-browser: true
  allowed-packages: 'com.vaadin,org.vaadin,dev.hilla,com.example.application'
spring:
  mustache:
    check-template-location: false
  datasource:
    url: 'jdbc:mysql://${DB_ADDR}:3306/${DB_NAME}'
    username: '${DB_USER}'
    password: '${DB_PASS}'
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
